[package]
name = "1axen/secure-cast"
version = "1.0.0"
description = "A server-authoritative projectile system for ROBLOX."
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["src/shared/SecureCast", "wally.toml", "wally.lock", "default.project.json", "README.md", "LICENSE"]
exclude = [""]

[dependencies]
